title: Rules of Court
remote_theme: opendocsg/opendoc-theme@v2
timezone: Asia/Singapore
repository: opendocsg/opendoc-rules-of-court
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
google_analytics:  #----> Optional, Google analytics ID
preload_pages: false
order:
  - "1-ORDER 1 - Citation, application, definitions and forms.md"
  - "2-ORDER 2 - Effect of non-compliance.md"
  - "3-ORDER 3 - Time.md"
  - "4-ORDER 4 - Consolidation of proceedings.md"
  - "5-ORDER 5 - Mode of beginning civil proceedings.md"
  - "6-ORDER 6 - Writs of summons- General provisions.md"
  - "7-ORDER 7 - Originating summonses- General provisions.md"
  - "8-ORDER 8.md"
  - "9-ORDER 9.md"
  - "10-ORDER 10 - Service of originating process- General provisions.md"
  - "11-ORDER 11 - Service process out of Singapore.md"
  - "12-ORDER 12 - Entry of appearance.md"
  - "13-ORDER 13 - Default of appearance to writ.md"
  - "14-ORDER 14 - Summary judgment and disposal of case on point of law.md"
  - "15-ORDER 15 - Causes of action- Counterclaims and parties.md"
  - "16-ORDER 16 - Third party and similar proceedings.md"
  - "17-ORDER 17 - Interpleader.md"
  - "18-ORDER 18 - Pleadings.md"
  - "19-ORDER 19 - Default of pleadings.md"
  - "20-ORDER 20 - Amendment.md"
  - "21-ORDER 21 - Withdrawal and discontinuance.md"
  - "22-ORDER 22 - Payment into and out of court.md"
  - "23-ORDER 22A - Offer to settle.md"
  - "24-ORDER 23 - Security for costs.md"
  - "25-ORDER 24 - Discovery and inspection of documents.md"
  - "26-ORDER 25 - Summons for directions.md"
  - "27-ORDER 26 - Interrogatories.md"
  - "28-ORDER 26A - Interrogatories before action, etc.md"
  - "29-ORDER 27 - Admissions.md"
  - "30-ORDER 28 - Originating summons procedure.md"
  - "31-ORDER 29 - Interlocutory injunctions, interim preservation of property, interim payments, etc.md"
  - "32-ORDER 30 - Receivers.md"
  - "33-ORDER 31 - Sale, etc, of immovable property by order of court.md"
  - "34-ORDER 32 - Applications and proceedings in chambers.md"
  - "35-ORDER 33 - Mode of trial.md"
  - "36-ORDER 34 - Setting down for trial of action begun by writ.md"
  - "37-ORDER 34A - Pre-trial conferences.md"
  - "38-ORDER 35 - Proceedings at trial.md"
  - "39-ORDER 36 - Trials before and inquiries by Registrar.md"
  - "40-ORDER 37 - Assessment of damages.md"
  - "41-ORDER 38 - Evidence- General.md"
  - "42-ORDER 38A - Official record of hearing.md"
  - "43-ORDER 39 - Evidence by deposition- Examiners of court.md"
  - "44-ORDER 40 - Court expert.md"
  - "45-ORDER 40A - Experts of parties.md"
  - "46-ORDER 41 - Affidavits.md"
  - "47-ORDER 42 - Judgments and orders.md"
  - "48-ORDER 43 - Accounts and inquiries.md"
  - "49-ORDER 44.md"
  - "50-ORDER 45 - Enforcement of judgments and orders.md"
  - "51-ORDER 46 - Writs of execution- General.md"
  - "52-ORDER 47 - Writs of seizure and sale.md"
  - "53-ORDER 48 - Examination of judgment debtor, etc.md"
  - "54-ORDER 49 - Garnishee proceedings.md"
  - "55-ORDER 50 - Stop orders, etc.md"
  - "56-ORDER 51 - Receivers- Equitable execution.md"
  - "57-ORDER 52 - Contempt of court.md"
  - "58-ORDER 53 - Application for Mandatory Order, Prohibiting Order, Quashing Order, etc.md"
  - "59-ORDER 54 - Application for Order for Review of Detention.md"
  - "60-ORDER 55 - Appeals to High Court from court, tribunal or person.md"
  - "61-ORDER 55A - Applications to High Court by case stated.md"
  - "62-ORDER 55B - Appeals from Registrar in proceedings in State Courts.md"
  - "63-ORDER 55C - Appeals from District Judges in Chambers.md"
  - "64-ORDER 55D - Appeals from State Courts.md"
  - "65-ORDER 56 - Appeals from Registrar and Judge in proceedings in Supreme Court.md"
  - "66-ORDER 57 - Appeals to Court of Appeal.md"
  - "67-ORDER 58 - References under Article 100 of Constitution for advisory opinion.md"
  - "68-ORDER 58A - Constitutional Case.md"
  - "69-ORDER 59 - Costs.md"
  - "70-ORDER 60 - The Registry.md"
  - "71-ORDER 61 - Sittings, vacation and office hours.md"
  - "72-ORDER 62 - Service of documents.md"
  - "73-ORDER 63 - Paper, printing, notices and copies.md"
  - "74-ORDER 63A - Electronic filing service.md"
  - "75-ORDER 64 - Change of solicitor.md"
  - "76-ORDER 65 - Service of foreign process.md"
  - "77-ORDER 66 - Obtaining evidence for foreign courts, etc.md"
  - "78-ORDER 67 - Reciprocal enforcement of judgments.md"
  - "79-ORDER 68.md"
  - "80-ORDER 69 - Arbitral proceedings.md"
  - "81-ORDER 69A - International Arbitration Act.md"
  - "82-ORDER 70 - Admiralty proceedings.md"
  - "83-ORDER 71.md"
  - "84-ORDER 72 - Contentious probate proceedings.md"
  - "85-ORDER 73 - Proceedings by and against Government.md"
  - "86-ORDER 74 - Debtors Act.md"
  - "87-ORDER 75 - Distress Act.md"
  - "88-ORDER 76 - Disability.md"
  - "89-ORDER 77 - Partners.md"
  - "90-ORDER 78 - Defamation actions.md"
  - "91-ORDER 79 - Moneylenders' actions.md"
  - "92-ORDER 80 - Administration and similar actions.md"
  - "93-ORDER 81 - Summary proceedings for possession of land.md"
  - "94-ORDER 82 - Debenture holders' action- Receiver's register.md"
  - "95-ORDER 83 - Mortgage actions.md"
  - "96-ORDER 84.md"
  - "97-ORDER 84A.md"
  - "98-ORDER 84B.md"
  - "99-ORDER 85 - Bills of Sale Act.md"
  - "100-ORDER 85A - Proceedings arising out of hire-purchase agreements.md"
  - "101-ORDER 86.md"
  - "102-ORDER 87 - Trade Marks Act.md"
  - "103-ORDER 87A - Patents Act.md"
  - "104-ORDER 88 - Companies Act.md"
  - "105-ORDER 89 - State Courts Act.md"
  - "106-ORDER 89A - Corruption, Drug Trafficking and Other Serious Crimes (Confiscation of Benefits) Act.md"
  - "107-ORDER 89B - Mutual Assistance in Criminal Matters Act.md"
  - "108-ORDER 89C - Employment Act.md"
  - "109-ORDER 89D - Oaths and Declarations Act.md"
  - "110-ORDER 89E - Terrorism (Suppression of Financing) Act.md"
  - "111-ORDER 90 - Lodgment in Court, money in Registry and payment to Sheriff.md"
  - "112-ORDER 90A - Hearing fees and Court ADR fees.md"
  - "113-ORDER 90B - Court fees for core bundle, etc.md"
  - "114-ORDER 91 - Court fees.md"
  - "115-ORDER 92 - Miscellaneous.md"
  - "116-ORDER 93 - Securities and Futures Act - Civil liability actions.md"
  - "117-ORDER 94 - Securities and Futures Act - Civil penalty actions.md"
  - "118-ORDER 95 - Building and Construction Industry Security of Payment Act.md"
  - "119-ORDER 96 - Limited Liability Partnerships Act.md"
  - "120-ORDER 97 - Competition Act - Applications under section 85 of Competition Act.md"
  - "121-ORDER 98 - Income Tax Act.md"
  - "122-ORDER 99.md"
  - "123-ORDER 100 - Collective sale applications.md"
  - "124-ORDER 101 - Referrals on issues of law.md"
  - "125-ORDER 102.md"
  - "126-ORDER 103 - Securities and Futures Act - Order for disgorgement against third party.md"
  - "127-ORDER 104.md"
  - "128-ORDER 105 - Personal Data Protection Act 2012.md"
  - "129-ORDER 106.md"
  - "130-ORDER 107.md"
  - "131-ORDER 108 - Simplified process for proceedings in Magistrate's Court or District Court.md"
  - "132-ORDER 109 - Protection from Harassment Act 2014.md"
  - "133-ORDER 110 - Singapore International Commercial Court.md"
  - "134-ORDER 111 - Choice of Court Agreements Act 2016.md"
  - "135-ORDER 112 - UNMERITORIOUS OR VEXATIOUS PROCEEDINGS.md"
  - "136-ORDER 113 - VEXATIOUS LITIGANTS.md"
  - "137-APPENDIX A - Forms.md"
  - "138-APPENDIX B - Court Fees.md"
  - "139-APPENDIX BA - Court Fees in the Singapore International Commercial Court.md"
  - "140-APPENDIX C - Civil Procedure Conventions.md"
  - "141-APPENDIX D - Endnotes.md"
  - "142-Legislative History.md"
styling_options:
  primary_brand_color: '#9f0836'
  logo_path: /assets/logo.png  #----> Optional, path to logo
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url:  #----> Optional, feedback url
  
